### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by kprodinfo** [askesaske/kprod.agency-test#1]
1. Девушка - растровая графика, она не должна быть в SVG
2. При медленном интернете показатель CLS очень плохой
3. Почему вдруг для шрифта без засечек, вы указываете семейство шрифтов с засечками, это также влияет и на CLS и на общее впечатление
4. Нету ни одного ховера, кроме cursor: pointer
5. -----------------------------
6. В фоне нету "пятен"
7. -----------------------------
8. Не вижу полоски
9. Очень печально с адаптивом. Вам было бы удобно пользоваться таким сайтом?

Даём вам еще одну попытку исправить указанные проблемы. Два пункта мы решили не озвучивать. Просто еще раз изучите макет и найдите, что вы забыли сделать.

**Comment by kprodinfo** [comment]
И пожалуйста - пусть в репозитории будет скомпилированный проект. У нас 30 тестовых пришло, каждый раз компилировать не хочется.

**Comment by askesaske** [comment]
Спасибо за ваш респонс.
1. В требованиях указано не использовать растровую графику.
2. Показатель CLS плохой, возможно. Но прошу посмотреть на специфичное расположение элементов. Учитывая требование "каждый элемент фона и иллюстраций нужно сделать отдельным слоем, а не объединённой картинкой".
3. Без комментариев, нет возможности проверить.
4. В макете не прорисованы никакие состояния, и в требованиях ничего. Но я мог бы добавить, да согласен. Это 2 сорочки кода.
6. Эти пятна едва заметны, с такими то цветами. Тоже самое и про полоски, я подумал что это дизайнер использовал их для построения сетки и забыл убрать. Учитывая то что макет прорисован крайне криво, начиная от группировки элементов и заканчивая размером элементов. 
7. Про адаптив все верно, в какой то момент на ширине ~600 ничего уже не видно. Я осознанно так оставил, если вы хотели проверить умения и навыки, то я все продемонстрировал.
8. Не старался сделать идеально, а просто показать что знаю, в принципе по написанному коду можно составить представление. При хорошо прорисованном макете, и составленном тз, никаких проблем не будет.
9. Я не голодный студент)))
